# Generated by Django 5.2.10 on 2026-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=4)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('effective_date', models.DateField()),
            ],
            options={
                'ordering': ['-effective_date', 'code'],
                'unique_together': {('code', 'effective_date')},
            },
        ),
    ]
